<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59017773"><DocLocation><![CDATA[C:\Users\GSRILAXM\Documents\Unified Functional Testing\Excel_demo]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Excel_demo]]></DName>
<Res><![CDATA[Res5]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 12:27:59]]></Time>
<TimeTick>1676271479</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 12:27:59]]></Time>
<TimeTick>1676271479</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ agentName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["swara"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:00]]></Time>
<TimeTick>1676271480</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="18" >
<Disp><![CDATA[[ agentName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ password ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:00]]></Time>
<TimeTick>1676271480</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ password ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ WpfButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:01]]></Time>
<TimeTick>1676271481</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action1" SourceLine="21" >
<Disp><![CDATA[[ WpfButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:26]]></Time>
<TimeTick>1676271506</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:26]]></Time>
<TimeTick>1676271506</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="22" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ agentName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pravin"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:27]]></Time>
<TimeTick>1676271507</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="Action1" SourceLine="18" >
<Disp><![CDATA[[ agentName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ password ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["singh"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:27]]></Time>
<TimeTick>1676271507</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="29" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ password ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ WpfButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:28]]></Time>
<TimeTick>1676271508</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="31" Source="Action1" SourceLine="21" >
<Disp><![CDATA[[ WpfButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:34]]></Time>
<TimeTick>1676271514</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:34]]></Time>
<TimeTick>1676271514</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="35" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="34" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ agentName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pratiksha"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:35]]></Time>
<TimeTick>1676271515</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" Source="Action1" SourceLine="18" >
<Disp><![CDATA[[ agentName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ password ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["singh"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:35]]></Time>
<TimeTick>1676271515</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ password ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ WpfButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:36]]></Time>
<TimeTick>1676271516</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="Action1" SourceLine="21" >
<Disp><![CDATA[[ WpfButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:41]]></Time>
<TimeTick>1676271521</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:41]]></Time>
<TimeTick>1676271521</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="47" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="46" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ agentName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["nitesh"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:42]]></Time>
<TimeTick>1676271522</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" Source="Action1" SourceLine="18" >
<Disp><![CDATA[[ agentName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ password ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["kumar"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:43]]></Time>
<TimeTick>1676271523</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="53" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ password ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ WpfButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:43]]></Time>
<TimeTick>1676271523</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="55" Source="Action1" SourceLine="21" >
<Disp><![CDATA[[ WpfButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:49]]></Time>
<TimeTick>1676271529</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:49]]></Time>
<TimeTick>1676271529</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="59" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="58" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ agentName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["srilaxmi"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:50]]></Time>
<TimeTick>1676271530</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="63" Source="Action1" SourceLine="18" >
<Disp><![CDATA[[ agentName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ password ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["gandrathi"]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:50]]></Time>
<TimeTick>1676271530</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="65" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ password ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ WpfButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:28:51]]></Time>
<TimeTick>1676271531</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" Source="Action1" SourceLine="21" >
<Disp><![CDATA[[ WpfButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:29]]></Time>
<TimeTick>1676271569</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:29]]></Time>
<TimeTick>1676271569</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="71" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="70" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ agentName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["susmitha"]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:30]]></Time>
<TimeTick>1676271570</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" Source="Action1" SourceLine="18" >
<Disp><![CDATA[[ agentName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ password ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["jukuri"]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:30]]></Time>
<TimeTick>1676271570</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="77" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ password ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ WpfButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:31]]></Time>
<TimeTick>1676271571</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="79" Source="Action1" SourceLine="21" >
<Disp><![CDATA[[ WpfButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:36]]></Time>
<TimeTick>1676271576</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:36]]></Time>
<TimeTick>1676271576</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="83" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="82" status="Passed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ agentName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["shobitha"]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:37]]></Time>
<TimeTick>1676271577</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="87" Source="Action1" SourceLine="18" >
<Disp><![CDATA[[ agentName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ password ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["b"]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:37]]></Time>
<TimeTick>1676271577</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="89" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ password ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ WpfButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:29:38]]></Time>
<TimeTick>1676271578</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="91" Source="Action1" SourceLine="21" >
<Disp><![CDATA[[ WpfButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-02-2023 - 12:27:53" eTime="13-02-2023 - 12:29:41" passed="7" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Excel_demo Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-02-2023 - 12:27:52" eTime="13-02-2023 - 12:29:41" passed="7" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Excel_demo Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>