<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59017773"><DocLocation><![CDATA[C:\Users\GSRILAXM\Documents\Unified Functional Testing\call_to_copy_demo]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[call_to_copy_demo]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login99]]></AName>
<Action rID="T5">
<AName><![CDATA[Copy of Action1]]></AName>
<AIter rID="T6" iterID="1" isCountable="False" >
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:37]]></Time>
<TimeTick>1676454037</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Welcome: Mercury Tours<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demo.guru99.com/test/newtours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:37]]></Time>
<TimeTick>1676454037</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:37]]></Time>
<TimeTick>1676454037</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[REGISTER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:37]]></Time>
<TimeTick>1676454037</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[REGISTER.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["GANDRATHI"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SRI LAXMI"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="Copy of Action1" SourceLine="2" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7989932408"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="Copy of Action1" SourceLine="3" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18gandrathisrilaxmi@gmail.com"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="29" Source="Copy of Action1" SourceLine="4" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5-61,kakatiya nagar"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="32" Source="Copy of Action1" SourceLine="5" >
<Disp><![CDATA[address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["bayyaram"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" Source="Copy of Action1" SourceLine="6" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Telangana"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="38" Source="Copy of Action1" SourceLine="7" >
<Disp><![CDATA[state.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["507211"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="41" Source="Copy of Action1" SourceLine="8" >
<Disp><![CDATA[postalCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["INDIA"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="44" Source="Copy of Action1" SourceLine="9" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18gandrathisrilaxmi@gmail.com"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:40]]></Time>
<TimeTick>1676454040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" Source="Copy of Action1" SourceLine="10" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e4737470e37fcfb565a53c2f9707a71a216d7d9809a6a2"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:41]]></Time>
<TimeTick>1676454041</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" Source="Copy of Action1" SourceLine="11" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[confirmPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e47380404ad4f1493941760e74c94fa107c80efa48ef10"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:41]]></Time>
<TimeTick>1676454041</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="53" Source="Copy of Action1" SourceLine="12" >
<Disp><![CDATA[confirmPassword.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="19" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="12" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="10" >
<Disp><![CDATA[Copy of Action1 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T24" iterID="2" isCountable="False" >
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:41]]></Time>
<TimeTick>1676454041</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (3 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Welcome: Mercury Tours<SPAN class=Failed> (Skipped)</SPAN><br>title=Welcome: Mercury Tours<SPAN class=Failed> (Skipped)</SPAN><br>openurl=https://demo.guru99.com/test/newtours<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>opentitle=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:41]]></Time>
<TimeTick>1676454041</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:41]]></Time>
<TimeTick>1676454041</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[REGISTER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:41]]></Time>
<TimeTick>1676454041</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[REGISTER.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="60" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:42]]></Time>
<TimeTick>1676454042</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["GANDRATHI"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:42]]></Time>
<TimeTick>1676454042</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="65" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SRI LAXMI"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:42]]></Time>
<TimeTick>1676454042</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="68" Source="Copy of Action1" SourceLine="2" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7989932408"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:42]]></Time>
<TimeTick>1676454042</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="71" Source="Copy of Action1" SourceLine="3" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18gandrathisrilaxmi@gmail.com"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:42]]></Time>
<TimeTick>1676454042</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" Source="Copy of Action1" SourceLine="4" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5-61,kakatiya nagar"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:43]]></Time>
<TimeTick>1676454043</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" Source="Copy of Action1" SourceLine="5" >
<Disp><![CDATA[address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["bayyaram"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:43]]></Time>
<TimeTick>1676454043</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="80" Source="Copy of Action1" SourceLine="6" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Telangana"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:43]]></Time>
<TimeTick>1676454043</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="83" Source="Copy of Action1" SourceLine="7" >
<Disp><![CDATA[state.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["507211"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:43]]></Time>
<TimeTick>1676454043</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="86" Source="Copy of Action1" SourceLine="8" >
<Disp><![CDATA[postalCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["INDIA"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:43]]></Time>
<TimeTick>1676454043</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="89" Source="Copy of Action1" SourceLine="9" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18gandrathisrilaxmi@gmail.com"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:43]]></Time>
<TimeTick>1676454043</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="92" Source="Copy of Action1" SourceLine="10" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e4737470e37fcfb565a53c2f9707a71a216d7d9809a6a2"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:43]]></Time>
<TimeTick>1676454043</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="95" Source="Copy of Action1" SourceLine="11" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[confirmPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e47380404ad4f1493941760e74c94fa107c80efa48ef10"]]></Details>
<Time><![CDATA[15-02-2023 - 15:10:43]]></Time>
<TimeTick>1676454043</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="98" Source="Copy of Action1" SourceLine="12" >
<Disp><![CDATA[confirmPassword.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="64" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="57" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="55" >
<Disp><![CDATA[Copy of Action1 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</AIter>
<Summary sTime="15-02-2023 - 15:10:36" eTime="15-02-2023 - 15:10:43" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="9" >
<Disp><![CDATA[Copy of Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="15-02-2023 - 15:10:36" eTime="15-02-2023 - 15:10:43" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Login99 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[call_to_copy_demo Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="15-02-2023 - 15:10:32" eTime="15-02-2023 - 15:10:43" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test call_to_copy_demo Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>