<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59017773"><DocLocation><![CDATA[C:\Users\GSRILAXM\Documents\Unified Functional Testing\demo_on_datatable_1]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[demo_on_datatable_1]]></DName>
<Res><![CDATA[Res10]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:03]]></Time>
<TimeTick>1675943103</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:03]]></Time>
<TimeTick>1675943103</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="login" SourceLine="0" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["63e4a385bfe8816217c0"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:03]]></Time>
<TimeTick>1675943103</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="login" SourceLine="1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:03]]></Time>
<TimeTick>1675943103</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="login" SourceLine="2" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="login" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="09-02-2023 - 17:15:02" eTime="09-02-2023 - 17:15:03" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T9">
<AName><![CDATA[selectflight]]></AName>
<AIter rID="T10" iterID="1" isCountable="False" >
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:04]]></Time>
<TimeTick>1675943104</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:04]]></Time>
<TimeTick>1675943104</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="selectflight" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:04]]></Time>
<TimeTick>1675943104</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" Source="selectflight" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[WpfImage.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[148, 107]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:05]]></Time>
<TimeTick>1675943105</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" Source="selectflight" SourceLine="2" >
<Disp><![CDATA[WpfImage.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:05]]></Time>
<TimeTick>1675943105</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="selectflight" SourceLine="3" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:06]]></Time>
<TimeTick>1675943106</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" Source="selectflight" SourceLine="4" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:06]]></Time>
<TimeTick>1675943106</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="selectflight" SourceLine="5" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[4, 1]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:06]]></Time>
<TimeTick>1675943106</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" Source="selectflight" SourceLine="6" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:07]]></Time>
<TimeTick>1675943107</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="selectflight" SourceLine="7" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["srilaxmi"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:07]]></Time>
<TimeTick>1675943107</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" Source="selectflight" SourceLine="8" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:07]]></Time>
<TimeTick>1675943107</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" Source="selectflight" SourceLine="9" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:07]]></Time>
<TimeTick>1675943107</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="selectflight" SourceLine="10" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="19" Source="selectflight" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="17" >
<Disp><![CDATA[selectflight Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T23" iterID="2" isCountable="False" >
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:08]]></Time>
<TimeTick>1675943108</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:08]]></Time>
<TimeTick>1675943108</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="45" Source="selectflight" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:08]]></Time>
<TimeTick>1675943108</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="47" Source="selectflight" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[WpfImage.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[148, 107]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:08]]></Time>
<TimeTick>1675943108</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" Source="selectflight" SourceLine="2" >
<Disp><![CDATA[WpfImage.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Economy"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:09]]></Time>
<TimeTick>1675943109</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="51" Source="selectflight" SourceLine="3" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:09]]></Time>
<TimeTick>1675943109</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" Source="selectflight" SourceLine="4" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:09]]></Time>
<TimeTick>1675943109</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="55" Source="selectflight" SourceLine="5" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[4, 1]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:10]]></Time>
<TimeTick>1675943110</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" Source="selectflight" SourceLine="6" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:10]]></Time>
<TimeTick>1675943110</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="59" Source="selectflight" SourceLine="7" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["susmitha"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:10]]></Time>
<TimeTick>1675943110</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="61" Source="selectflight" SourceLine="8" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:10]]></Time>
<TimeTick>1675943110</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="63" Source="selectflight" SourceLine="9" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:11]]></Time>
<TimeTick>1675943111</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="65" Source="selectflight" SourceLine="10" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="44" Source="selectflight" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="42" >
<Disp><![CDATA[selectflight Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T36" iterID="3" isCountable="False" >
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:11]]></Time>
<TimeTick>1675943111</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:11]]></Time>
<TimeTick>1675943111</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="70" Source="selectflight" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:11]]></Time>
<TimeTick>1675943111</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="72" Source="selectflight" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[WpfImage.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[148, 107]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:12]]></Time>
<TimeTick>1675943112</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" Source="selectflight" SourceLine="2" >
<Disp><![CDATA[WpfImage.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["First"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:12]]></Time>
<TimeTick>1675943112</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="76" Source="selectflight" SourceLine="3" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:12]]></Time>
<TimeTick>1675943112</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="78" Source="selectflight" SourceLine="4" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:13]]></Time>
<TimeTick>1675943113</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="80" Source="selectflight" SourceLine="5" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[4, 1]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:13]]></Time>
<TimeTick>1675943113</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" Source="selectflight" SourceLine="6" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:13]]></Time>
<TimeTick>1675943113</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="84" Source="selectflight" SourceLine="7" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["nandini"]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:13]]></Time>
<TimeTick>1675943113</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="86" Source="selectflight" SourceLine="8" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:14]]></Time>
<TimeTick>1675943114</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="88" Source="selectflight" SourceLine="9" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:14]]></Time>
<TimeTick>1675943114</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="90" Source="selectflight" SourceLine="10" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="69" Source="selectflight" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="67" >
<Disp><![CDATA[selectflight Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</AIter>
<Summary sTime="09-02-2023 - 17:15:04" eTime="09-02-2023 - 17:15:14" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="16" >
<Disp><![CDATA[selectflight Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T49">
<AName><![CDATA[logout]]></AName>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:15]]></Time>
<TimeTick>1675943115</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-02-2023 - 17:15:15]]></Time>
<TimeTick>1675943115</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="96" Source="logout" SourceLine="1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="95" Source="logout" SourceLine="1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="09-02-2023 - 17:15:14" eTime="09-02-2023 - 17:15:15" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="93" >
<Disp><![CDATA[logout Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[demo_on_datatable_1 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="09-02-2023 - 17:14:48" eTime="09-02-2023 - 17:15:15" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test demo_on_datatable_1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>