<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59017773"><DocLocation><![CDATA[C:\Users\GSRILAXM\Documents\Unified Functional Testing\call_to_copy_demo]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[call_to_copy_demo]]></DName>
<Res><![CDATA[Res8]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login99]]></AName>
<Action rID="T5">
<AName><![CDATA[Copy of Action1]]></AName>
<AIter rID="T6" iterID="1" isCountable="False" >
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[15-02-2023 - 15:47:52]]></Time>
<TimeTick>1676456272</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[15-02-2023 - 15:47:52]]></Time>
<TimeTick>1676456272</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="14" status="Passed" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="13" status="Passed" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 15:47:53]]></Time>
<TimeTick>1676456273</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (4 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (4 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Welcome: Mercury Tours<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demo.guru99.com/test/newtours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-02-2023 - 15:47:53]]></Time>
<TimeTick>1676456273</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:00]]></Time>
<TimeTick>1676456280</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[REGISTER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:00]]></Time>
<TimeTick>1676456280</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[REGISTER.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="19" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:01]]></Time>
<TimeTick>1676456281</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["GANDRATHI"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:01]]></Time>
<TimeTick>1676456281</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="24" Source="Copy of Action1" SourceLine="2" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SRI LAXMI"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:01]]></Time>
<TimeTick>1676456281</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" Source="Copy of Action1" SourceLine="3" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7989932408"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:02]]></Time>
<TimeTick>1676456282</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" Source="Copy of Action1" SourceLine="4" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18gandrathisrilaxmi@gmail.com"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:02]]></Time>
<TimeTick>1676456282</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" Source="Copy of Action1" SourceLine="5" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5-61,kakatiya nagar"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:02]]></Time>
<TimeTick>1676456282</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" Source="Copy of Action1" SourceLine="6" >
<Disp><![CDATA[address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["bayyaram"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:02]]></Time>
<TimeTick>1676456282</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" Source="Copy of Action1" SourceLine="7" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Telangana"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:02]]></Time>
<TimeTick>1676456282</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" Source="Copy of Action1" SourceLine="8" >
<Disp><![CDATA[state.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["507211"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:02]]></Time>
<TimeTick>1676456282</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="45" Source="Copy of Action1" SourceLine="9" >
<Disp><![CDATA[postalCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["INDIA"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:02]]></Time>
<TimeTick>1676456282</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="48" Source="Copy of Action1" SourceLine="10" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:03]]></Time>
<TimeTick>1676456283</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="51" Source="Copy of Action1" SourceLine="11" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e4737470e37fcfb565a53c2f9707a71a216d7d9809a6a2"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:03]]></Time>
<TimeTick>1676456283</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="54" Source="Copy of Action1" SourceLine="12" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[confirmPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e47380404ad4f1493941760e74c94fa107c80efa48ef10"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:03]]></Time>
<TimeTick>1676456283</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" Source="Copy of Action1" SourceLine="13" >
<Disp><![CDATA[confirmPassword.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="23" Source="Copy of Action1" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="10" status="Passed" >
<Disp><![CDATA[Copy of Action1 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T26" iterID="2" isCountable="False" >
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:03]]></Time>
<TimeTick>1676456283</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:03]]></Time>
<TimeTick>1676456283</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="63" status="Passed" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="62" status="Passed" Source="Copy of Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:06]]></Time>
<TimeTick>1676456286</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (5 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (5 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Welcome: Mercury Tours<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demo.guru99.com/test/newtours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:06]]></Time>
<TimeTick>1676456286</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:07]]></Time>
<TimeTick>1676456287</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[REGISTER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:07]]></Time>
<TimeTick>1676456287</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[REGISTER.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="68" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:08]]></Time>
<TimeTick>1676456288</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["GANDRATHI"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:08]]></Time>
<TimeTick>1676456288</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" Source="Copy of Action1" SourceLine="2" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SRI LAXMI"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:08]]></Time>
<TimeTick>1676456288</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="76" Source="Copy of Action1" SourceLine="3" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7989932408"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:08]]></Time>
<TimeTick>1676456288</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="79" Source="Copy of Action1" SourceLine="4" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18gandrathisrilaxmi@gmail.com"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:08]]></Time>
<TimeTick>1676456288</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" Source="Copy of Action1" SourceLine="5" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5-61,kakatiya nagar"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:08]]></Time>
<TimeTick>1676456288</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="85" Source="Copy of Action1" SourceLine="6" >
<Disp><![CDATA[address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["bayyaram"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:09]]></Time>
<TimeTick>1676456289</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="88" Source="Copy of Action1" SourceLine="7" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Telangana"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:09]]></Time>
<TimeTick>1676456289</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="91" Source="Copy of Action1" SourceLine="8" >
<Disp><![CDATA[state.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["507211"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:09]]></Time>
<TimeTick>1676456289</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="94" Source="Copy of Action1" SourceLine="9" >
<Disp><![CDATA[postalCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["INDIA"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:09]]></Time>
<TimeTick>1676456289</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="97" Source="Copy of Action1" SourceLine="10" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:09]]></Time>
<TimeTick>1676456289</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="100" Source="Copy of Action1" SourceLine="11" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e4737470e37fcfb565a53c2f9707a71a216d7d9809a6a2"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:09]]></Time>
<TimeTick>1676456289</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="103" Source="Copy of Action1" SourceLine="12" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[confirmPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e47380404ad4f1493941760e74c94fa107c80efa48ef10"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:09]]></Time>
<TimeTick>1676456289</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="106" Source="Copy of Action1" SourceLine="13" >
<Disp><![CDATA[confirmPassword.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="72" Source="Copy of Action1" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="65" Source="Copy of Action1" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="59" status="Passed" >
<Disp><![CDATA[Copy of Action1 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</AIter>
<Summary sTime="15-02-2023 - 15:47:52" eTime="15-02-2023 - 15:48:09" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[Copy of Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T46">
<AName><![CDATA[Action1 [Trisentis_Demo]]]></AName>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:10]]></Time>
<TimeTick>1676456290</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA["Demo Web Shop"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (5 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (5 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Demo Web Shop<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Demo Web Shop<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demowebshop.tricentis.com<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Demo Web Shop<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:10]]></Time>
<TimeTick>1676456290</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="112" Source="Action1 [Trisentis_Demo]" SourceLine="0" >
<Disp><![CDATA["Demo Web Shop"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:10]]></Time>
<TimeTick>1676456290</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:10]]></Time>
<TimeTick>1676456290</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="115" Source="Action1 [Trisentis_Demo]" SourceLine="0" >
<Disp><![CDATA[Log in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="114" Source="Action1 [Trisentis_Demo]" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:11]]></Time>
<TimeTick>1676456291</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18gandrathisrilaxmi@gmail.com"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:11]]></Time>
<TimeTick>1676456291</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="120" Source="Action1 [Trisentis_Demo]" SourceLine="1" >
<Disp><![CDATA[Email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e4754d897e7a5d4247ea28e9c6bbffcf41955af84d56b7"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:11]]></Time>
<TimeTick>1676456291</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="123" Source="Action1 [Trisentis_Demo]" SourceLine="2" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:11]]></Time>
<TimeTick>1676456291</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="126" Source="Action1 [Trisentis_Demo]" SourceLine="3" >
<Disp><![CDATA[Log in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="119" Source="Action1 [Trisentis_Demo]" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:13]]></Time>
<TimeTick>1676456293</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[q.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["computer"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:13]]></Time>
<TimeTick>1676456293</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="130" Source="Action1 [Trisentis_Demo]" SourceLine="4" >
<Disp><![CDATA[q.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:13]]></Time>
<TimeTick>1676456293</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="133" Source="Action1 [Trisentis_Demo]" SourceLine="5" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="129" Source="Action1 [Trisentis_Demo]" SourceLine="4" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:14]]></Time>
<TimeTick>1676456294</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Picture of Build your.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:14]]></Time>
<TimeTick>1676456294</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="137" Source="Action1 [Trisentis_Demo]" SourceLine="6" >
<Disp><![CDATA[Picture of Build your.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="136" Source="Action1 [Trisentis_Demo]" SourceLine="6" >
<Disp><![CDATA[Demo Web Shop. Search]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Build your]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:25]]></Time>
<TimeTick>1676456305</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[product_attribute_72_8_30.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:25]]></Time>
<TimeTick>1676456305</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="141" Source="Action1 [Trisentis_Demo]" SourceLine="7" >
<Disp><![CDATA[product_attribute_72_8_30.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Add to cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 15:48:25]]></Time>
<TimeTick>1676456305</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="144" Source="Action1 [Trisentis_Demo]" SourceLine="8" >
<Disp><![CDATA[Add to cart.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="140" Source="Action1 [Trisentis_Demo]" SourceLine="7" >